* Sway Config
Config files and a couple of default backgrounds that I use on sway.

Curently two branches, laptop and desktop, but will probably merge laptop into master and nuke both soon; this config is (mostly) working fine for me in both environments.

I've left comments in Sway's config detailing how to lookup things like mice/keyboards etc.

** Requirements
 - brightnessctl
 - wlogout
 - swayidle
 - gvfs
 - xorg-xwayland (if want to run X11 apps)
 - [[https://google.com][Other stuff I've probably forgotten.]]

** Bar - WayBar
I choose this pretty much because most of the other Wayland compatible bars had uglier configurartion to setup.  I still want something as simple as Polynar for themeing though; I've never liked cascading style sheets.

** Menu - Wofi
Found here.
It's a menu, it looks nice, it works for me.

** Window manager - Alacritty/Foot
Found here.
It all comes down to Emacs and theming.  Using foot an a slightly convoluted way to invoke Emacs, I can get Emacs to use the default terminal colours.  But with Alacritty, it uses the Emacs defaults.  Wait a minute....

** File Manager - Thunar
Found here
Really only used to make dealing with removable media less of a pain.

* To Do
 - [ ] Add GTK3 theme
 - [ ] Add Kora icons
 - [ ] Fix the annoying layout issues.
 - [ ] Get volume/mute keys working.
   - [ ] Use css to add a divider between items (i.e. right-border).
   - [ ] Find better icons for pulseaudio.
 - [ ] Script (Janet) to preiew different backends for py-wal?
 - [ ] Look into the Emacs theme again, if foot is causing stability issues, will need to go back to Alacritty.
 - [ ] Custom kernel, fuck it - rice hard or erm, just install a regular destop and actualy have a life.  Dammit.....
 - [ ] Add bluetooth suport at some point if just for completeness as a desktop!  Hardly ever use it, if at all.
 - [X] Find out why Waybar "desktop" numbers are displayed in black
